server:
  port: 8088

spring:
  application:
    name: TurnosMicroService

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/turnos_db?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: 

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        hibernate.type.preferred_uuid_jdbc_type: BINARY
        dialect: org.hibernate.dialect.MySQL8Dialect

# IMPORTANTE: Ahora apunta al Gateway, no directo al microservicio
usuarios:
  service:
    url: http://localhost:8089/usuarios # CORREGIDO! Apuntando al Gateway en 8089


whatsapp:
  api:
    url: https://api.whatsapp.example/send
    token: ${WHATSAPP_API_TOKEN:TU_TOKEN_AQUI}

turnos:
  tolerancia-minutos: 10
  min-duration-minutes: 45
  buffer-minutes: 5