server:
  port: 8089

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:

        # ----------------------------------
        #  Microservicio de Cat�logo
        # ----------------------------------
        - id: catalogo-service
          uri: http://localhost:8083
          predicates:
            - Path=/catalogo/**

        # ----------------------------------
        #  Microservicio de Turnos
        # ----------------------------------
        - id: turnos-service
          uri: http://localhost:8088
          predicates:
            - Path=/turnos/**

        # ----------------------------------
        #  Microservicio de Usuarios
        # ----------------------------------
        - id: usuarios-service
          uri: http://localhost:8085
          predicates:
            - Path=/usuarios/**

        # ----------------------------------
        #  Microservicio de Autenticaci�n
        # ----------------------------------
        - id: auth-service
          uri: http://localhost:8084
          predicates:
            - Path=/auth/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/MicroservicesBarber
          jwk-set-uri: http://localhost:8080/realms/MicroservicesBarber/protocol/openid-connect/certs

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG

